//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptianDictionary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        public string Glyph { get; set; }
        public string Unicode { get; set; }
        public string Categoria { get; set; }
        public string GardinerCode { get; set; }
        public string Description { get; set; }
        public string Phonogram { get; set; }
        public string Transliteration { get; set; }
        public string Notes { get; set; }
    
        public virtual Categoria Categoria1 { get; set; }
    }
}
