//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptianDictionary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary_ru
    {
        public string glyph { get; set; }
        public string unicode { get; set; }
        public string categoria { get; set; }
        public string gardiner_code { get; set; }
        public string description { get; set; }
        public string phonogram { get; set; }
        public string transliteration { get; set; }
        public string notes { get; set; }
    
        public virtual Categoria_ru Categoria_ru { get; set; }
    }
}
