//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptianDictionary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class God_ru
    {
        public string name { get; set; }
        public string gardiner_code { get; set; }
        public string hieroglyphic { get; set; }
        public string transliteration { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public string view { get; set; }
    }
}
