//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptianDictionary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharaoh
    {
        public string Name { get; set; }
        public string BirthName { get; set; }
        public string BirthDescription { get; set; }
        public string ThroneName { get; set; }
        public string ThroneDescription { get; set; }
        public string Dynasty { get; set; }
    }
}
