//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptianDictionary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phonogram
    {
        public string Glyph { get; set; }
        public string GardinerCode { get; set; }
        public string Transliteration { get; set; }
        public string ManuelCotage { get; set; }
        public string Type { get; set; }
    }
}
