//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptianDictionary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        public byte Id { get; set; }
        public byte ClientId { get; set; }
        public Nullable<byte> TranslatorId { get; set; }
        public string OriginalText { get; set; }
        public string Task { get; set; }
        public string Result { get; set; }
        public string ClientName { get; set; }
        public string TranslatorName { get; set; }

        public virtual Client Client { get; set; }
        public virtual Translator Translator { get; set; }
    }
}
